-- Run with: lua tests/duel_spec.lua (from repository root)
local Duel = dofile("mod/AZWade-RiskOfRainBrawlers/duel.lua")
local d = Duel.new({wins_required = 3, max_health = 100})
assert(d.phase == "ready")
d:start_round()
assert(d:damage("commando", 40) == false)
assert(d.health.commando == 60)
assert(d:ring_out("commando") == true)
assert(d.wins.mercenary == 1 and d.phase == "round_over")
assert(d:ring_out("commando") == false) -- no duplicate scoring
d:start_round()
assert(d.health.commando == 100)
assert(d:damage("mercenary", 100) == true)
assert(d.wins.commando == 1)
d:start_round()
assert(d:ring_out("mercenary") == true)
d:start_round()
assert(d:damage("mercenary", 110) == true)
assert(d.winner == "commando" and d.phase == "match_over")
assert(d.round_number == 4)
d:reset_match()
assert(d.winner == nil and d.wins.commando == 0 and d.round_number == 0)
print("duel_spec: passed")
